### ISSUE TITLE
stage4 solution has duplicated classes

### ISSUE THREAD

**Issue by RedJocker** [hatepoint/phrases-hyperskill-tests#17]
there are several duplicated classes on your solution for stage4

- phrases.PhrasesAdapter X phrases.data.PhrasesAdapter
- phrases.MainActivity  X phrases.ui.MainActivity
- phases.TimePickerDialog X phrases.ui.TimePickerDialog

the MainActivity that is declared on manifest is phrases.MainActivity

**Comment by hatepoint** [comment]
Fixed (left everything in main package: not the way I wanted but atleast it isn't supposed to break)
