### ISSUE TITLE
RecyclerView.assertListItems

### ISSUE THREAD

**Issue by hatepoint** [hatepoint/phrases-hyperskill-tests#2]
It's not quite clear for me how this method can be used. What is the second argument (`assertItems: (itemViewSupplier...`) is needed for?
I made a workaround for checking the number of items in the tests avoiding this function but I would like to know how to do it correctly.

**Comment by hatepoint** [comment]
@RedJocker

**Comment by RedJocker** [comment]
this is from the examples repository (https://github.com/RedJocker/hyperskillRoboletricExample/blob/main/Project%20Name/SqliteStorageExample/src/test/java/org/hyperskill/projectname/Stage1UnitTest.kt#L114-L127)

```
            rvList.assertListItems(expectedList) { itemViewSupplier, index, item ->
                val itemView = itemViewSupplier()
                val listItemTvTitle = itemView.findViewByString<TextView>("listItemTvTitle")
                val listItemTvDescription = itemView.findViewByString<TextView>("listItemTvDescription")


                val expectedTitle = item.first
                val expectedDescription = item.second


                val actualTitle = listItemTvTitle.text.toString()
                val actualDescription = listItemTvDescription.text.toString()


                assertEquals("wrong title", expectedTitle, actualTitle)
                assertEquals("wrong description", expectedDescription, actualDescription)
            }
```

I used to pass just itemView, but I had problems with that whenever there where state changes requiring solution to call notifyItemChanged. When that happens the recyclerView may change the View instance for that list item so tests then need to refresh the view reference by calling the supplier again.

**Comment by hatepoint** [comment]
I think I might use more than just size checking, so I'll let you know how it went

**Comment by RedJocker** [comment]
I think I can close this, if you need further clarifications for this method you can reopen this issue
