### ISSUE TITLE
layout for RecyclerView items 

### ISSUE THREAD

**Issue by RedJocker** [hatepoint/phrases-hyperskill-tests#5]
I don't see any layout for list items on the recycler view. I see some findViewByString() with ids that are probably intended for items on the recyclerView, but I cannot confirm that by looking at the items layout because it is not there.

**Comment by hatepoint** [comment]
I thought that this project shouldn't have solutions, so I remove them manually after writing tests. I guess I was wrong and that I should remove solution only when all tests are ready.

You can check the dev/stage2 branch - there is a solution in a e547361be81be0ff34d3ac5e6f06c079ad2a77f4 commit

**Comment by RedJocker** [comment]
> I thought that this project shouldn't have solutions. 

Not a concern on this phase of the project, now we want to write tests and having a solution is needed. To tests the tests and to have a complete picture of the stage. Sometimes the solution has to fixed too.

**Comment by RedJocker** [comment]
the solution on that commit is for all stages isn't it? 
It think it would be better to have a solution for that fits each stage, but ok I guess we don't have time for that. 
Can you please add that solution back here. I can't test the test code against a implemetation that is on commit back in history.

**Comment by hatepoint** [comment]
Yeah, it's for all stages. I was too lazy to rewrite the project and just copy-pasted. I will rewrite it to fit for each stage, this shouldn't take much time. I'll close the issue when solutions will be added

**Comment by hatepoint** [comment]
43f87bf56845e48bd06f1c8538bfa6ad57c6929b now has solution for stage 2, I tried modifying the solution to see whether tests work and so far they seem to be fine.
